apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: ecomm-outbox
  namespace: ecomm-streaming
  annotations:
    strimzi.io/restart: "1770195221"
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: pg-ha-primary.db.svc.cluster.local
    database.port: "5432"
    database.user: debezium
    database.password: dbz
    database.dbname: ecomm
    plugin.name: pgoutput
    slot.name: ecomm_outbox_slot
    publication.name: dbz_outbox_pub
    publication.autocreate.mode: disabled
    table.include.list: cart.outbox_event,catalog.outbox_event,orders.outbox_event,payment.outbox_event,shipping.outbox_event
    topic.prefix: ecomm
    snapshot.mode: no_data
    transforms: outbox
    transforms.outbox.type: io.debezium.transforms.outbox.EventRouter
    transforms.outbox.route.by.field: aggregate_type
    transforms.outbox.route.topic.replacement: ecomm.${routedByValue}
    transforms.outbox.table.field.event.id: aggregate_id
    transforms.outbox.table.field.event.key: aggregate_id
    transforms.outbox.table.field.event.type: event_type
    transforms.outbox.table.field.event.payload: payload
    transforms.outbox.table.field.event.timestamp: created_at
    transforms.outbox.table.expand.json.payload: "true"
