apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: app
        image: ghcr.io/printesh99/payment-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "ecomm-kafka-kafka-bootstrap.ecomm-streaming.svc.cluster.local:9092"
        - name: PGHOST
          value: "pg-ha-primary.db.svc.cluster.local"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "ecomm"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "postgres"
        readinessProbe:
          httpGet: { path: /healthz, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - name: http
    port: 80
    targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: payment-service
spec:
  to:
    kind: Service
    name: payment-service
  port:
    targetPort: http
